version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: incomeinequality_airflow
    container_name: incomeinequality_airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/app/airflow/dags  # Mount DAGs directory

  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: incomeinequality_flask
    container_name: incomeinequality_flask
    ports:
      - "80:80"
    depends_on:
      - airflow  # Wait for Airflow container to be ready
